version: "3"
services:
  mongodb:
    image: mongo
    container_name: mogodb_1
    restart: always
    ports:
      - 27017:27017

# this is the dashboard. We start it first so that it can create all the tables correctly
  springboot-jobrunr-dashboard:
    image: app.jar
    environment:
      SPRING_DATA_MONGODB_DATABASE: user_db
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_HOST: mongodb
      ORG_JOBRUNR_DATABASE_SKIP_CREATE: "false"
      ORG_JOBRUNR_DATABASE_TABLE_PREFIX: "demo"
      ORG_JOBRUNR_JOB-SCHEDULER_EBABLED: "true"
      ORG_JOBRUNR_BACKGROUND_JOB_SERVER_ENABLED: "false"
      ORG_JOBRUNR_DASHBOARD_ENABLED: "true"
      ORG_JOBRUNR_BACKGROUND_JOB_SERVER_PERMANENTLY_DELETE_DELETEDJOBS_AFTER: "1"

    ports:
      - "9001:9001"
      - "8080:8080"
    build:
      context: .
      dockerfile: "Dockerfile"
    depends_on:
      - mongodb

# this is the background job server. It depends on the dashboard so that it does not try to create the tables twice.
# We can scale this using docker compose up --scale springboot-backend=3
  springboot-backend:
    image: app.jar
    environment:
      SPRING_DATA_MONGODB_DATABASE: user_db
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_HOST: mongodb
      ORG_JOBRUNR_DATABASE_SKIP_CREATE: "false"
      ORG_JOBRUNR_DATABASE_TABLE_PREFIX: "demo"
      ORG_JOBRUNR_JOB-SCHEDULER_EBABLED: "false"
      ORG_JOBRUNR_BACKGROUND_JOB_SERVER_ENABLED: "true"
      ORG_JOBRUNR_BACKGROUND_JOB_SERVER_PERMANENTLY_DELETE_DELETEDJOBS_AFTER: "1"
    build:
      context: .
      dockerfile: "Dockerfile"
    depends_on:
      - mongodb
      - springboot-jobrunr-dashboard

networks:
  default:
    driver: bridge
